### ISSUE TITLE
Unable to run the code.

### ISSUE THREAD

**Issue by prashantTejam84** [alexfdez1010/exam-generator#1]
(venv) XXXX@ZZZZ exam-generator-master % streamlit run app.py 
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py

**Comment by alexfdez1010** [comment]
There is a typo in the docs. Should be main.py instead of app.py. It has already been solved in the Readme.md

**Comment by prashantTejam84** [comment]
I tried running - streamlit run main.py before your updates however still there is an error after clicking 'Genearte' - "An error occurred while generating the questions. Please try again"

**Comment by prashantTejam84** [comment]
Thanks for updating Readme

**Comment by alexfdez1010** [comment]
That error occurs sometimes. It is related to GPT-3.5. As it is non deterministic sometimes generates a text that cannot be parsed by the application to convert into a quiz. The prompt used for GPT-3.5 is the best that I could figure out, but fails sometimes. If there is an error try with the same topics another time.

**Comment by prashantTejam84** [comment]
It never worked for me for any topic. Anyways, thanks for looking into it.
